passed: False, 

 output: ============================= test session starts ==============================
platform darwin -- Python 3.11.4, pytest-8.3.3, pluggy-1.5.0 -- /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
cachedir: .pytest_cache
rootdir: /Users/dude/projects/python/algo-training
plugins: langsmith-0.4.4, anyio-3.7.1
collecting ... collected 1 item

warmup.py::test_counter FAILED                                           [100%]

=================================== FAILURES ===================================
_________________________________ test_counter _________________________________
warmup.py:33: in test_counter
    assert c.get_value() == 1
E   assert 2 == 1
E    +  where 2 = get_value()
E    +    where get_value = <warmup.Counter object at 0x10349fcd0>.get_value
=========================== short test summary info ============================
FAILED warmup.py::test_counter - assert 2 == 1
============================== 1 failed in 0.03s ===============================
