passed: False, 

 output: ============================= test session starts ==============================
platform darwin -- Python 3.11.4, pytest-8.3.3, pluggy-1.5.0 -- /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
cachedir: .pytest_cache
rootdir: /Users/dude/projects/python/algo-training
plugins: langsmith-0.4.4, anyio-3.7.1
collecting ... collected 1 item

warmup.py::test_merge_sort FAILED                                        [100%]

=================================== FAILURES ===================================
_______________________________ test_merge_sort ________________________________
warmup.py:13: in test_merge_sort
    assert merge_sort([3,1,4,1,5]) == [1,1,3,4,5]
E   assert None == [1, 1, 3, 4, 5]
E    +  where None = merge_sort([3, 1, 4, 1, 5])
=========================== short test summary info ============================
FAILED warmup.py::test_merge_sort - assert None == [1, 1, 3, 4, 5]
============================== 1 failed in 0.02s ===============================
